MAKEFLAGS += -j4

# Functions
rwildcard = $(foreach d,$(wildcard $(1:=/*)), $(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))

# Compiler flags
CXX      := g++
CXXFLAGS := -std=c++20 -pedantic-errors -Wno-format-security -Wno-sign-compare -DSFML_STATIC -DIMGUI_USE_WCHAR32

# Targets
TARGET := meckt.exe

# Directories
SFML_DIR    := vendor/sfml
SRC_DIR     := src
INCLUDE_DIR := src
VENDOR_DIR  := vendor
BIN_DIR     := build/bin
OBJ_DIR     := build/bin/obj
INCLUDE     := -I$(INCLUDE_DIR) -I$(VENDOR_DIR)/includes -I$(VENDOR_DIR)/includes/jomini-parser/src -I$(SFML_DIR)/include

# Sources and objects
SRC := $(call rwildcard,$(SRC_DIR),*.cpp) \
       $(VENDOR_DIR)/includes/imgui/sfml/imgui-SFML.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/imgui.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/imgui_demo.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/imgui_widgets.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/imgui_draw.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/imgui_tables.cpp \
       $(VENDOR_DIR)/includes/imgui/imgui/misc/cpp/imgui_stdlib.cpp \
	   $(VENDOR_DIR)/includes/jomini-parser/src/Jomini.cpp

PCH_HEADER   := $(SRC_DIR)/pch.hpp
PCH          := $(PCH_HEADER:%.h=$(OBJ_DIR)/%.gch)
OBJECTS      := $(SRC:%.cpp=$(OBJ_DIR)/%.o)
DEPENDENCIES := $(OBJECTS:.o=.d)

# Build type (default: release)
BUILD_TYPE := release
ifeq ($(BUILD_TYPE),debug)
    CXXFLAGS += -O0 -DDEBUG -g
else ifeq ($(BUILD_TYPE),release)
    CXXFLAGS += -O3 -DNDEBUG
endif

# Libraries
LDFLAGS := -L$(VENDOR_DIR)/lib/fmt -lfmt_win \
           -L$(VENDOR_DIR)/lib/nfd -lnfd_win -lcomctl32 -lole32 -luuid \
           -L$(SFML_DIR)/lib/ -lsfml-graphics-s -lsfml-window-s -lsfml-system-s \
           -lopengl32 -lfreetype -lgdi32 -lwinmm -ldsound -lws2_32 -lwinhttp \
           -ldbghelp -lpsapi \
           -static-libgcc -static-libstdc++ -static

.PHONY: all build clean info run

all: build $(BIN_DIR)/$(TARGET)

# Precompiled header target
$(PCH): $(PCH_HEADER)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $(INCLUDE) -x c++-header $(PCH_HEADER) -MMD -MP -o $(PCH)

# Object files
$(OBJ_DIR)/%.o: %.cpp $(PCH)
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $(INCLUDE) -c $< -MMD -MP -o $@ -include $(PCH_HEADER)

-include $(DEPENDENCIES)

# Executable target
$(BIN_DIR)/$(TARGET): $(OBJECTS)
	@mkdir -p $(@D)
	windres $(SRC_DIR)/build/version.rc -o $(OBJ_DIR)/$(SRC_DIR)/build/version.o
	$(CXX) $(CXXFLAGS) $(OBJ_DIR)/$(SRC_DIR)/build/version.o -o $(BIN_DIR)/$(TARGET) $^ $(LDFLAGS)

# Make commands
build:
	@clear
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(OBJ_DIR)
	@cp -ar assets/. $(BIN_DIR)/assets

run:
	@./$(BIN_DIR)/$(TARGET)

clean:
	-@rm -rvf $(OBJ_DIR)/* $(BIN_DIR)/*

info:
	@echo "Target: ${TARGET}"
	@echo "Sources: ${SRC}"
	@echo "Application dir: ${BIN_DIR}"
	@echo "Object dir: ${OBJ_DIR}"
	@echo "Objects: ${OBJECTS}"
	@echo "Dependencies: ${DEPENDENCIES}"
